services:
  db:
    image: mariadb:10.6.11
    container_name: budgets.db
    restart: always
    ports:
      - "3333:3306"
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}