# Generated by Django 4.2.4 on 2023-09-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupobudgets', '0002_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='lang',
            field=models.CharField(max_length=6),
        ),
    ]
