# Generated by Django 4.2.4 on 2023-09-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lupobudgets', '0003_alter_translation_lang'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('key', 'lang')},
        ),
    ]
