# Generated by Django 4.2.4 on 2023-09-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lupobudgets', '0004_alter_translation_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
